-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.api_key
(
    api_key_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    key character varying COLLATE pg_catalog."default" NOT NULL,
    secret character varying COLLATE pg_catalog."default" NOT NULL,
    status api_key_status_enum NOT NULL DEFAULT 'active'::api_key_status_enum,
    program_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    promoter_id uuid,
    CONSTRAINT "PK_febd1522b7c552bbe6987e7b51f" PRIMARY KEY (api_key_id),
    CONSTRAINT "UQ_fb080786c16de6ace7ed0b69f7d" UNIQUE (key)
);

CREATE TABLE IF NOT EXISTS public.circle
(
    circle_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    is_default_circle boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    program_id uuid NOT NULL,
    CONSTRAINT "PK_08744ec19c2b01f4c29faacc393" PRIMARY KEY (circle_id)
);

CREATE TABLE IF NOT EXISTS public.circle_promoter
(
    circle_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_4ff1a30947984b4a64bfda525be" PRIMARY KEY (circle_id, promoter_id)
);

CREATE TABLE IF NOT EXISTS public.commission
(
    commission_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    conversion_type commission_conversion_type_enum NOT NULL,
    external_id uuid NOT NULL,
    amount numeric NOT NULL,
    revenue numeric,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    contact_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    link_id uuid NOT NULL,
    CONSTRAINT "PK_2459aaa9caa0ee8ef88cd60911d" PRIMARY KEY (commission_id)
);

CREATE TABLE IF NOT EXISTS public.condition
(
    condition_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    parameter condition_parameter_enum NOT NULL,
    operator condition_operator_enum NOT NULL,
    value character varying COLLATE pg_catalog."default" NOT NULL,
    function_id uuid,
    CONSTRAINT "PK_842f840ae3a680df42ab08c8616" PRIMARY KEY (condition_id)
);

CREATE TABLE IF NOT EXISTS public.contact
(
    contact_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying COLLATE pg_catalog."default",
    first_name character varying COLLATE pg_catalog."default",
    external_id character varying COLLATE pg_catalog."default",
    last_name character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    status contact_status_enum NOT NULL DEFAULT 'lead'::contact_status_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    program_id uuid NOT NULL,
    CONSTRAINT "PK_b77c91f220387c3c90df787bce5" PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.function
(
    function_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    trigger function_trigger_enum NOT NULL,
    effect_type function_effect_type_enum NOT NULL DEFAULT 'generate_commission'::function_effect_type_enum,
    effect jsonb NOT NULL,
    status function_status_enum NOT NULL DEFAULT 'active'::function_status_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    circle_id uuid NOT NULL,
    program_id uuid NOT NULL,
    CONSTRAINT "PK_6129f598a8df4ea4aaadd8b929f" PRIMARY KEY (function_id)
);

CREATE TABLE IF NOT EXISTS public.link
(
    link_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    ref_val character varying COLLATE pg_catalog."default" NOT NULL,
    status link_status_enum NOT NULL DEFAULT 'active'::link_status_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    program_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    CONSTRAINT "PK_2c169f0fae14774f9787954ae6f" PRIMARY KEY (link_id)
);

CREATE TABLE IF NOT EXISTS public.link_analytics_day_wise_mv
(
    date date NOT NULL,
    link_id uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    ref_val character varying COLLATE pg_catalog."default" NOT NULL,
    program_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    signups numeric DEFAULT 0,
    purchases numeric DEFAULT 0,
    commission numeric DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT link_analytics_day_wise_mv_pkey PRIMARY KEY (date, link_id)
);

CREATE TABLE IF NOT EXISTS public.link_analytics_mv
(
    link_id uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    ref_val character varying COLLATE pg_catalog."default" NOT NULL,
    program_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    signups numeric DEFAULT 0,
    purchases numeric DEFAULT 0,
    commission numeric DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT link_analytics_mv_pkey PRIMARY KEY (link_id)
);

CREATE TABLE IF NOT EXISTS public.member
(
    member_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    program_id uuid,
    normalized_email character varying COLLATE pg_catalog."default",
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (COALESCE(normalized_email, ''::character varying))::text)) STORED,
    CONSTRAINT "PK_73e1828d94de0b2ddf89da05463" PRIMARY KEY (member_id),
    CONSTRAINT program_id_email_unique UNIQUE (program_id, email)
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.program
(
    program_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    website character varying COLLATE pg_catalog."default" NOT NULL,
    visibility program_visibility_enum NOT NULL DEFAULT 'public'::program_visibility_enum,
    currency character varying COLLATE pg_catalog."default" NOT NULL,
    referral_key_type program_referral_key_type_enum NOT NULL,
    logo_url character varying COLLATE pg_catalog."default",
    theme_color character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    terms_and_conditions character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    date_format program_date_format_enum NOT NULL DEFAULT 'DD/MM/YYYY'::program_date_format_enum,
    time_zone character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_53f58709c0270f634ebc233c52c" PRIMARY KEY (program_id)
);

CREATE TABLE IF NOT EXISTS public.program_promoter
(
    program_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    accepted_terms_and_conditions boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_962c05e02f60d5c579897e7ee18" PRIMARY KEY (program_id, promoter_id)
);

CREATE TABLE IF NOT EXISTS public.program_user
(
    program_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status program_user_status_enum NOT NULL DEFAULT 'active'::program_user_status_enum,
    role program_user_role_enum NOT NULL DEFAULT 'viewer'::program_user_role_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ca45ab30487a8daececdaa8a02f" PRIMARY KEY (program_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.promoter
(
    promoter_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    logo_url character varying COLLATE pg_catalog."default",
    status promoter_status_enum NOT NULL DEFAULT 'active'::promoter_status_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    normalized_name character varying COLLATE pg_catalog."default",
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (COALESCE(normalized_name, ''::character varying))::text)) STORED,
    CONSTRAINT "PK_f496acc776e708cae318d49c16a" PRIMARY KEY (promoter_id)
);

CREATE TABLE IF NOT EXISTS public.promoter_analytics_day_wise_mv
(
    date date NOT NULL,
    promoter_id uuid NOT NULL,
    program_id uuid NOT NULL,
    revenue numeric DEFAULT 0,
    commission numeric DEFAULT 0,
    signups numeric DEFAULT 0,
    purchases numeric DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    signup_commission numeric,
    purchase_commission numeric,
    CONSTRAINT promoter_analytics_day_wise_mv_pkey PRIMARY KEY (date, promoter_id, program_id)
);

CREATE TABLE IF NOT EXISTS public.promoter_analytics_mv
(
    promoter_id uuid NOT NULL,
    program_id uuid NOT NULL,
    total_revenue numeric DEFAULT 0,
    total_commission numeric DEFAULT 0,
    total_signups numeric DEFAULT 0,
    total_purchases numeric DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    signup_commission numeric,
    purchase_commission numeric,
    CONSTRAINT promoter_analytics_mv_pkey PRIMARY KEY (promoter_id, program_id)
);

CREATE TABLE IF NOT EXISTS public.promoter_member
(
    promoter_id uuid NOT NULL,
    member_id uuid NOT NULL,
    status promoter_member_status_enum NOT NULL DEFAULT 'active'::promoter_member_status_enum,
    role promoter_member_role_enum NOT NULL DEFAULT 'viewer'::promoter_member_role_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_6ceb1b5a3d8db6a61d86e795b2e" PRIMARY KEY (promoter_id, member_id)
);

CREATE TABLE IF NOT EXISTS public.purchase
(
    purchase_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    item_id character varying COLLATE pg_catalog."default" NOT NULL,
    contact_id uuid NOT NULL,
    amount numeric NOT NULL,
    utm_params jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    promoter_id uuid NOT NULL,
    link_id uuid NOT NULL,
    CONSTRAINT "PK_fb8b774c1e9156a025b67133750" PRIMARY KEY (purchase_id)
);

CREATE TABLE IF NOT EXISTS public.referral_mv
(
    program_id uuid NOT NULL,
    promoter_id uuid NOT NULL,
    contact_id uuid NOT NULL,
    status contact_status_enum NOT NULL,
    contact_info character varying COLLATE pg_catalog."default" NOT NULL,
    total_revenue numeric DEFAULT 0,
    total_commission numeric DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    normalized_contact_info character varying COLLATE pg_catalog."default",
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, (COALESCE(normalized_contact_info, ''::character varying))::text)) STORED,
    CONSTRAINT referral_mv_pkey PRIMARY KEY (program_id, promoter_id, contact_id)
);

CREATE TABLE IF NOT EXISTS public.sign_up
(
    contact_id uuid NOT NULL,
    utm_params jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    promoter_id uuid NOT NULL,
    link_id uuid NOT NULL,
    CONSTRAINT "PK_c795a64a8956593dc834d5d278b" PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.typeorm_metadata
(
    type character varying COLLATE pg_catalog."default" NOT NULL,
    database character varying COLLATE pg_catalog."default",
    schema character varying COLLATE pg_catalog."default",
    "table" character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    value text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default" NOT NULL,
    role user_role_enum NOT NULL DEFAULT 'regular'::user_role_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_758b8ce7c18b9d347461b30228d" PRIMARY KEY (user_id),
    CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.webhook
(
    webhook_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    url character varying COLLATE pg_catalog."default" NOT NULL,
    program_id uuid NOT NULL,
    secret character varying COLLATE pg_catalog."default" NOT NULL,
    events character varying[] COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_d6a804c21e268e248929f763ef9" PRIMARY KEY (webhook_id)
);

ALTER TABLE IF EXISTS public.api_key
    ADD CONSTRAINT "FK_api_key_promoter_id" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.api_key
    ADD CONSTRAINT "FK_b5b356e8c1c4fc6e1532047b7d1" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.circle
    ADD CONSTRAINT "FK_a633e8b1bd1b9971472346194e8" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.circle_promoter
    ADD CONSTRAINT "FK_359058f838541320812ce0c9527" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.circle_promoter
    ADD CONSTRAINT "FK_b82beaf48ef7171c478962dbe2b" FOREIGN KEY (circle_id)
    REFERENCES public.circle (circle_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.commission
    ADD CONSTRAINT "FK_66e005fb863cf9415bfe00e5209" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.commission
    ADD CONSTRAINT "FK_80d0bf1d09df59e050ebcbf9523" FOREIGN KEY (contact_id)
    REFERENCES public.contact (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.commission
    ADD CONSTRAINT "FK_955b396caf603c299b735fd41c7" FOREIGN KEY (link_id)
    REFERENCES public.link (link_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.condition
    ADD CONSTRAINT "FK_ff56e8b916122f2ed65abb5598b" FOREIGN KEY (function_id)
    REFERENCES public.function (function_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.contact
    ADD CONSTRAINT "FK_c369b0744b568b57e873cf88918" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_contact_program_id
    ON public.contact(program_id);


ALTER TABLE IF EXISTS public.function
    ADD CONSTRAINT "FK_879b535e416a2458ce582322d80" FOREIGN KEY (circle_id)
    REFERENCES public.circle (circle_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.function
    ADD CONSTRAINT "FK_f60276fc5f0fd8827d373d34300" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.link
    ADD CONSTRAINT "FK_04cc9a19abed9f69f007d2efbd1" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_link_promoter_id
    ON public.link(promoter_id);


ALTER TABLE IF EXISTS public.link
    ADD CONSTRAINT "FK_62f88b546b2692d3e1e0adde2c8" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_link_program_id
    ON public.link(program_id);


ALTER TABLE IF EXISTS public.member
    ADD CONSTRAINT "FK_494edefd8ea279114a413eb9c2a" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.program_promoter
    ADD CONSTRAINT "FK_2e7950ea53add840dc7d79d624a" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.program_promoter
    ADD CONSTRAINT "FK_93fe2cc5e07091fa30d7d22001a" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.program_user
    ADD CONSTRAINT "FK_d0aa650710ea93d56e39c8ec53c" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.program_user
    ADD CONSTRAINT "FK_fb84966f083d85ee02aebd75f9a" FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.promoter_member
    ADD CONSTRAINT "FK_67f29bc5b7be6abbbb1f9f04207" FOREIGN KEY (member_id)
    REFERENCES public.member (member_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.promoter_member
    ADD CONSTRAINT "FK_9e171d7ffe319fefc1d84702a64" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT "FK_a4ea159c479503d4b64fb223f58" FOREIGN KEY (link_id)
    REFERENCES public.link (link_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT "FK_b8d2f680be4de906782982abf91" FOREIGN KEY (contact_id)
    REFERENCES public.contact (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT "FK_e86d6010397e445ce2016d7880a" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sign_up
    ADD CONSTRAINT "FK_a819e2dcfb58d9a31647a169177" FOREIGN KEY (link_id)
    REFERENCES public.link (link_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sign_up
    ADD CONSTRAINT "FK_b98d88f092bcd1444537a281d39" FOREIGN KEY (promoter_id)
    REFERENCES public.promoter (promoter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sign_up
    ADD CONSTRAINT "FK_c795a64a8956593dc834d5d278b" FOREIGN KEY (contact_id)
    REFERENCES public.contact (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "PK_c795a64a8956593dc834d5d278b"
    ON public.sign_up(contact_id);


ALTER TABLE IF EXISTS public.webhook
    ADD CONSTRAINT "FK_4ead5f518f190a6fb249cec2e60" FOREIGN KEY (program_id)
    REFERENCES public.program (program_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;